### ISSUE TITLE
😺 

### ISSUE THREAD

**Issue by werbenhu** [mochi-co/equivalent-unified-ideograph#1]
@mochi-co I couldn't find your email, so I'm leaving you a message here. I believe you can invite active collaborators like dgduncan, thedevop, or other proactive individuals to join the mochi-mqtt organization. You can create a team under any name without granting any permissions; this would greatly boost everyone's motivation. If you've read this message, please close this issue.

**Comment by mochi-co** [comment]
@werbenhu Thank you! I had not idea this was possible, I think I must have misunderstood how it works. I've added you and a few others to a new developers team with Write permissions.

Also yes I'll try to get a contact email together for github 🤔 I'll close this issue but feel free to reply here in the meantime. Much appreciated!
